
["Umbrellas Durability"]
	#The durability in seconds of the Diamond Umbrella when in the sun. Set to -1 if you want it to be unbreakable
	#Range: -1 ~ 432000
	diamondUmbrellaDurability = 28800
	#The durability in seconds of the Gold Umbrella when in the sun. Set to -1 if you want it to be unbreakable
	#Range: -1 ~ 432000
	goldUmbrellaDurability = 14400
	#The durability in seconds of the Iron Umbrella when in the sun. Set to -1 if you want it to be unbreakable
	#Range: -1 ~ 432000
	ironUmbrellaDurability = 9600
	#The durability in seconds of the Netherite Umbrella when in the sun. Set to -1 if you want it to be unbreakable
	#Range: -1 ~ 432000
	netheriteUmbrellaDurability = 47600

["Umbrellas Mechanics"]
	#Set to false if you don't want the umbrella to work in the off-hand
	umbrellaOffHand = true
	#Set to false if you don't want the umbrella to be used in the curios slot
	umbrellaBauble = true
	#Set to false if you don't want the umbrella to work in the main-hand
	umbrellaMainHand = true
	#Set to false if you don't want the umbrella to be enchanted using anvils.
	umbrellaAnvil = false

[Others]
	#If true, the Creative Umbrella will respect the "umbrellaMainHand" and "umbrellaOffHand" configs.
	#If false, the Creative Umbrella will always works in main-hand and off-hand
	creativeUmbrellaConfigs = false

